package modelo;
// Generated 15 ene 2025, 12:30:59 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado implements java.io.Serializable {

	private String dni;
	private String nomEmp;
	private Set proyectos = new HashSet(0);
	private Set proyectos_1 = new HashSet(0);

	public Empleado() {
	}

	public Empleado(String dni, String nomEmp) {
		this.dni = dni;
		this.nomEmp = nomEmp;
	}

	public Empleado(String dni, String nomEmp, Set proyectos, Set proyectos_1) {
		this.dni = dni;
		this.nomEmp = nomEmp;
		this.proyectos = proyectos;
		this.proyectos_1 = proyectos_1;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getNomEmp() {
		return this.nomEmp;
	}

	public void setNomEmp(String nomEmp) {
		this.nomEmp = nomEmp;
	}

	public Set getProyectos() {
		return this.proyectos;
	}

	public void setProyectos(Set proyectos) {
		this.proyectos = proyectos;
	}

	public Set getProyectos_1() {
		return this.proyectos_1;
	}

	public void setProyectos_1(Set proyectos_1) {
		this.proyectos_1 = proyectos_1;
	}

}
