package modelo;
// Generated 15 ene 2025, 12:30:59 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto implements java.io.Serializable {

	private Integer idProy;
	private Empleado empleado;
	private String nomProy;
	private Set empleados = new HashSet(0);

	public Proyecto() {
	}

	public Proyecto(Empleado empleado, String nomProy) {
		this.empleado = empleado;
		this.nomProy = nomProy;
	}

	public Proyecto(Empleado empleado, String nomProy, Set empleados) {
		this.empleado = empleado;
		this.nomProy = nomProy;
		this.empleados = empleados;
	}

	public Integer getIdProy() {
		return this.idProy;
	}

	public void setIdProy(Integer idProy) {
		this.idProy = idProy;
	}

	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	public String getNomProy() {
		return this.nomProy;
	}

	public void setNomProy(String nomProy) {
		this.nomProy = nomProy;
	}

	public Set getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Set empleados) {
		this.empleados = empleados;
	}

}
