package modelo;
// Generated 15 ene 2025, 12:30:59 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto implements java.io.Serializable {

	private Integer idProy;
	private Empleado jefe;
	private String nomProy;
	private Set<Empleado> empleados = new HashSet<>(0);

	public Proyecto() {
	}

	public Proyecto(Empleado jefe, String nomProy) {
		this.jefe = jefe;
		this.nomProy = nomProy;
	}

	public Proyecto(Empleado jefe, String nomProy, Set<Empleado> empleados) {
		this.jefe = jefe;
		this.nomProy = nomProy;
		this.empleados = empleados;
	}

	public Integer getIdProy() {
		return this.idProy;
	}

	public void setIdProy(Integer idProy) {
		this.idProy = idProy;
	}

	public Empleado getJefe() {
		return this.jefe;
	}

	public void setJefe(Empleado jefe) {
		this.jefe = jefe;
	}

	public String getNomProy() {
		return this.nomProy;
	}

	public void setNomProy(String nomProy) {
		this.nomProy = nomProy;
	}

	public Set getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Set<Empleado> empleados) {
		this.empleados = empleados;
	}

}
